language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
env:
- SETTINGS='config.TestConfig'
script:
- source ./environment_test.sh
- py.test --cov thefeeder tests/ --cov-report=term --cov-report=html
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: Di9HVqJDZwgwMmskdEegP6omdUprlYhzyrvgiqucOpIpfuTPlyWSQ1NMIyaqrn2KNC0sXRtvgz3CjNsR53hqX24XWbBQTWQs7JJzOGL/6M5+9GwdiPhFaMcQaLjZ/aLVafaEVLUisyaXb/HVFoMFGQZZhcLQn6Xjbx06KXmIcWk=
  app: lr-feeder-app
  on:
    repo: LandRegistry/the-feeder
