language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
env:
- SETTINGS='TEST'
script: py.test --cov thefeeder tests/ --cov-report=term --cov-report=html
after_success:
  - coveralls
deploy:
  provider: heroku
  api_key:
    secure: KyQv94T0FBlYgSf5iEQett6POlGek2846w/bi0cNQVj/DTWxdvlghbsWpAPX5tQz1nrmmfGR7z+H8FoT0m6lcrWgJkx3KPAbLt9lmGQbjxC6bsaSxBaGRtHOGuEepa/f98USFAoHb6t4I4lUJU3ZGlSHvn9+C5lumncPp/ud8HA=
  app: lr-feeder-app
  on:
    repo: LandRegistry/the-feeder
